name: restaurant

services:
  mysql:
    image: mysql:latest
    container_name: pm-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sa2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # SQL initialization script

  image_server:
    build:
      context: ./image-server
    ports:
      - "8000:8000"
    volumes:
      - ./image-server/images:/app/images
    restart: always

  # backend:
  #   build:
  #     context: ./restaurant
  #   container_name: spring-boot-backend
  #   restart: always
  #   ports:
  #     - "8088:8088"
  #   volumes:
  #     - ./restaurant:/app
  #   depends_on:
  #     - mysql
  #   env_file:
  #     - ./restaurant/src/main/resources/.env
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sa2?serverTimezone=Asia/Bangkok
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=

  frontend:
    image: node:20
    container_name: vue-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm i && npm run dev -- --host 0.0.0.0"
